{
 "title": "Surveillance Kube-State Metrics",
 "panels": [
  {
   "title": "Pods non disponibles",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable)"
    }
   ]
  },
  {
   "title": "Nombre total de déploiements",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 6, "h": 6 },
   "targets": [
    { "expr": "count(kube_deployment_created)" }
   ]
  },
  {
   "title": "Pods en état Running",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase='Running'})"
    }
   ]
  }
 ]
}